name: acme-pcf

version: 0.1

# NOTE: Keep in sync with ./doctest/DocTest.hs and ./.stylish-haskell.yaml
#
# NOTE: StrictData is on.
default-extensions:
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - HexFloatLiterals
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - NamedFieldPuns
  - NegativeLiterals
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PackageImports
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TupleSections
  - TypeApplications
  - TypeOperators

ghc-options: -Wall

dependencies:

  # Notable

  - megaparsec == 8.0.0 # so I get notified if it updates
  - parser-combinators
  - relude

  # Other

  - aeson
  - aeson-pretty
  - base
  - bytestring
  - containers
  - string-qq
  - text
  - unordered-containers

library:
  source-dirs: src

executables:
  acme-pcf:
    source-dirs: .
    main: Main.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - acme-pcf
      - optparse-applicative

  acme-pcf-test:
    source-dirs: misc
    main: PcfTest.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - acme-pcf
      - optparse-applicative
      - typed-process

tests:
  doctest:
    source-dirs: doctest
    main: DocTest.hs
    dependencies:
      - acme-pcf
      - doctest
      - Glob

  spec:
    source-dirs: test
    main: Test.hs
    dependencies:
      - acme-pcf
      - hspec
