name: acme-pcf
version: 0.1
default-extensions:
  # NOTE: Keep in sync with ./doctest/DocTest.hs and ./.stylish-haskell.yaml

  # Notable

  - StrictData

  # Other

  - BlockArguments
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables

ghc-options: -Wall
dependencies:

  # Notable

  - megaparsec
  - parser-combinators

  # Other

  - aeson
  - aeson-pretty
  - base
  - bytestring
  - containers
  - string-qq
  - text
  - unordered-containers

library:
  source-dirs: src

executables:
  acme-pcf:
    source-dirs: .
    main: Main.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - acme-pcf
      - optparse-applicative

  acme-pcf-test:
    source-dirs: misc
    main: PCFTest.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - acme-pcf
      - optparse-applicative
      - typed-process

tests:
  doctest:
    source-dirs: doctest
    main: DocTest.hs
    dependencies:
      - acme-pcf
      - doctest
      - Glob

  spec:
    source-dirs: test
    main: Test.hs
    dependencies:
      - acme-pcf
      - hspec
