resolver: lts-13.29

# Make weeder work with stack 2:
# https://github.com/ndmitchell/weeder/issues/53
#
# (commented out because while it's on `stack ghci` dumps .dump-hi files everywhere)
#
# ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  - megaparsec-8.0.0 # important enough to lock down
