resolver: lts-16.6

# Make weeder work with stack 2:
# https://github.com/ndmitchell/weeder/issues/53
#
# (commented out because while it's on `stack ghci` dumps .dump-hi files everywhere)
#
# ghc-options: {"$locals": -ddump-to-file -ddump-hi}
